import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { PtAppGeneratedModule, PtAppGeneratedSharedModule } from './generated/module.js';
import { PtAppValidator, registerValidationChecks } from './pt-app-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type PtAppAddedServices = {
    validation: {
        PtAppValidator: PtAppValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type PtAppServices = LangiumServices & PtAppAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const PtAppModule: Module<PtAppServices, PartialLangiumServices & PtAppAddedServices> = {
    validation: {
        PtAppValidator: () => new PtAppValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createPtAppServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    PtApp: PtAppServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        PtAppGeneratedSharedModule
    );
    const PtApp = inject(
        createDefaultModule({ shared }),
        PtAppGeneratedModule,
        PtAppModule
    );
    shared.ServiceRegistry.register(PtApp);
    registerValidationChecks(PtApp);
    return { shared, PtApp };
}
